#!/bin/bash
set -e

# Install Deno
curl -fsSL https://deno.land/install.sh | sh
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# Install Deno Jupyter kernel (make sure to use the correct version and URL)
deno install -qAf --unstable https://deno.land/x/deno_jupyter_kernel@latest/install.ts
deno_jupyter_kernel install
